{"sections":[],"metadata":{"title":"didNotThrow","modules":[{"name":"SwiftMocking"}],"roleHeading":"Type Property","role":"symbol","externalID":"s:12SwiftMocking0B5ErrorV11didNotThrowACvpZ","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"didNotThrow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MockingError","preciseIdentifier":"s:12SwiftMocking0B5ErrorV"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError\/didNotThrow","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SwiftMocking\/documentation\/SwiftMocking","doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Indicates that a method was expected to throw an error, but it did not."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didNotThrow","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:12SwiftMocking0B5ErrorV","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError","text":"MockingError","kind":"typeIdentifier"}],"platforms":["macOS"]}]}],"variants":[{"paths":["\/documentation\/swiftmocking\/mockingerror\/didnotthrow"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SwiftMocking/documentation/SwiftMocking/MockingError/didNotThrow":{"url":"\/documentation\/swiftmocking\/mockingerror\/didnotthrow","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError\/didNotThrow","type":"topic","role":"symbol","title":"didNotThrow","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"didNotThrow","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:12SwiftMocking0B5ErrorV","text":"MockingError","kind":"typeIdentifier"}],"abstract":[{"text":"Indicates that a method was expected to throw an error, but it did not.","type":"text"}]},"doc://SwiftMocking/documentation/SwiftMocking":{"url":"\/documentation\/swiftmocking","type":"topic","kind":"symbol","title":"SwiftMocking","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking","abstract":[],"role":"collection"},"doc://SwiftMocking/documentation/SwiftMocking/MockingError":{"navigatorTitle":[{"kind":"identifier","text":"MockingError"}],"role":"symbol","url":"\/documentation\/swiftmocking\/mockingerror","kind":"symbol","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MockingError"}],"abstract":[{"text":"Represents an error that occurred during mocking or verification.","type":"text"}],"type":"topic","title":"MockingError"}}}