{"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didNotThrow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MockingError","preciseIdentifier":"s:12SwiftMocking0B5ErrorV"}],"externalID":"s:12SwiftMocking0B5ErrorV11didNotThrowACvpZ","title":"didNotThrow","modules":[{"name":"SwiftMocking"}],"symbolKind":"property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError\/didNotThrow"},"abstract":[{"text":"Indicates that a method was expected to throw an error, but it did not.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftmocking\/mockingerror\/didnotthrow"]}],"hierarchy":{"paths":[["doc:\/\/SwiftMocking\/documentation\/SwiftMocking","doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"didNotThrow","kind":"identifier"},{"kind":"text","text":": "},{"text":"MockingError","preciseIdentifier":"s:12SwiftMocking0B5ErrorV","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SwiftMocking/documentation/SwiftMocking/MockingError/didNotThrow":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didNotThrow","kind":"identifier"},{"kind":"text","text":": "},{"text":"MockingError","kind":"typeIdentifier","preciseIdentifier":"s:12SwiftMocking0B5ErrorV"}],"title":"didNotThrow","type":"topic","kind":"symbol","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError\/didNotThrow","abstract":[{"text":"Indicates that a method was expected to throw an error, but it did not.","type":"text"}],"role":"symbol","url":"\/documentation\/swiftmocking\/mockingerror\/didnotthrow"},"doc://SwiftMocking/documentation/SwiftMocking/MockingError":{"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MockingError","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MockingError"}],"type":"topic","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/MockingError","abstract":[{"text":"Represents an error that occurred during mocking or verification.","type":"text"}],"title":"MockingError","url":"\/documentation\/swiftmocking\/mockingerror"},"doc://SwiftMocking/documentation/SwiftMocking":{"url":"\/documentation\/swiftmocking","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking","type":"topic","role":"collection","abstract":[],"title":"SwiftMocking","kind":"symbol"}}}