{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Asynchronous","doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Effect","doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Throwing"],"kind":"relationships","type":"conformsTo"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/AsyncThrows"},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AsyncThrows","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/swiftmocking\/asyncthrows"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SwiftMocking\/documentation\/SwiftMocking"]]},"metadata":{"title":"AsyncThrows","role":"symbol","navigatorTitle":[{"text":"AsyncThrows","kind":"identifier"}],"symbolKind":"enum","externalID":"s:12SwiftMocking11AsyncThrowsO","roleHeading":"Enumeration","modules":[{"name":"SwiftMocking"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"AsyncThrows","kind":"identifier"}]},"abstract":[{"text":"Represents an asynchronous method that can also throw an error.","type":"text"}],"references":{"doc://SwiftMocking/documentation/SwiftMocking/Throwing":{"type":"topic","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Throwing","kind":"symbol","title":"Throwing","navigatorTitle":[{"kind":"identifier","text":"Throwing"}],"url":"\/documentation\/swiftmocking\/throwing","role":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Throwing"}]},"doc://SwiftMocking/documentation/SwiftMocking/Effect":{"kind":"symbol","title":"Effect","abstract":[{"type":"text","text":"A protocol that defines the effect of a method, such as throwing an error or being asynchronous."}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Effect","kind":"identifier"}],"identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Effect","navigatorTitle":[{"kind":"identifier","text":"Effect"}],"type":"topic","url":"\/documentation\/swiftmocking\/effect"},"doc://SwiftMocking/documentation/SwiftMocking/Asynchronous":{"title":"Asynchronous","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"Asynchronous","kind":"identifier"}],"identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/Asynchronous","navigatorTitle":[{"kind":"identifier","text":"Asynchronous"}],"abstract":[],"url":"\/documentation\/swiftmocking\/asynchronous","role":"symbol","kind":"symbol","type":"topic"},"doc://SwiftMocking/documentation/SwiftMocking/AsyncThrows":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AsyncThrows","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AsyncThrows"}],"abstract":[{"text":"Represents an asynchronous method that can also throw an error.","type":"text"}],"type":"topic","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking\/AsyncThrows","url":"\/documentation\/swiftmocking\/asyncthrows","title":"AsyncThrows","kind":"symbol"},"doc://SwiftMocking/documentation/SwiftMocking":{"url":"\/documentation\/swiftmocking","identifier":"doc:\/\/SwiftMocking\/documentation\/SwiftMocking","type":"topic","role":"collection","abstract":[],"title":"SwiftMocking","kind":"symbol"}}}